spring:
  application:
    name: eureka
    
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: false
  server:
    enableSelfPreservation: true

---

spring:
  profiles: peer1
  
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka2:8080/eureka/
  instance:
    hostname: eureka1
    prefer-ip-address: false
      
---

spring:
  profiles: peer2
  
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka1:8080/eureka/
  instance:
    hostname: eureka2
    prefer-ip-address: false