/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package es.microservice.spring.netflix.eureka;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        EurekaStarter classUnderTest = new EurekaStarter();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.testMethod());
    }
}
